### ISSUE TITLE
Total Sale count should include only paid (not pending)

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-dashboard#13]
<img width="444" alt="Screenshot 2019-05-10 at 09 52 20" src="https://user-images.githubusercontent.com/10923247/57511328-546f7000-7309-11e9-8303-33ad07799ef0.png">

**Comment by perminder-klair** [comment]
completed on API so should be fone

**Comment by dimarconicola** [comment]
No it's not done. @perminder-klair reopen it please.

<img width="365" alt="Screenshot 2019-05-10 at 10 47 22" src="https://user-images.githubusercontent.com/10923247/57514558-0f4f3c00-7311-11e9-90c0-5794bb312553.png">
