### ISSUE TITLE
Dashboard small bugs & improvements list

### ISSUE THREAD

**Issue by dimarconicola** [dexlab-io/dexpay-dashboard#3]
**Create products**
- [x] price shows a confusing $ icon next to the input
- [x] when successfully creating a product it should refresh to product list view (now stays on product creation)
- [ ] maybe validation should happen inline (i.e. preventing to type "," , special characters or letters)
- [x]  status "active" could be pre-selected
- [x] full description could have the label (optional)
- [x] there should be a loading indicator after clicking on "save"

**Invoice List**
- [x] The title should be "create an invoice" not "invoice create"

**Comment by dimarconicola** [comment]
We need to reopen this issue as I cannot even test it.

<img width="997" alt="Screenshot 2019-04-25 at 15 11 29" src="https://user-images.githubusercontent.com/10923247/56738258-83fc7500-676c-11e9-8fc6-fda17ce1e96f.png">

**Comment by perminder-klair** [comment]
@dimarconicola checking

**Comment by perminder-klair** [comment]
@dimarconicola on what page you getting this error? please paste link to it here

**Comment by perminder-klair** [comment]
fixed it @dimarconicola please test it again on your end if it is resolved.

**Comment by dimarconicola** [comment]
all good. I close this.
